#!/bin/bash

DEF=$(pactl get-default-sink)
VOL=$(pactl get-sink-volume $DEF | grep -ohP '\d+%' | head -n 1);

has_headset(){
  grep -A4 -ri 'Headphone Playback Switch' /proc/asound/card*/* | \
    grep "Amp-Out vals.*0x00 0x00" -q;
}

ICON=󰕾

if $(echo $DEF | grep 'blue'); then
		ICON=
elif $(has_headset); then
		ICON=󱡬
fi

echo $ICON $VOL
